#!/bin/bash

echo "Hi from $0 !"

# Show some info if we have any
test -n "$*" && echo  "Args: \"$*\""
test -n "$K_JOB_INDEX" && echo "Index: $K_JOB_INDEX"

# If we're streaming then just echo whatever comes across stdin, but reversed
while read line ; do
  echo "$line" | rev
done
