FROM golang
COPY taskmgr.go /src/
WORKDIR /src/
RUN go get -d ./...
RUN GO_EXTLINK_ENABLED=0 CGO_ENABLED=0 go build \
    -ldflags "-w -extldflags -static" \
	-tags netgo -installsuffix netgo \
	-o /taskmgr /src/taskmgr.go
CMD /taskmgr
