#!/bin/bash

set -e

# kn job create MYJOB --task=MYTASK --num=# --concurrency=# --retry=# -w
# kn job wait MYJOB
# kn job status MYJOB

if [[ "$1" == "create" ]]; then
  shift
  job="$1"
  shift

  while [[ "$1" == "--"* ]]; do
    opt="$1"
    case "$opt" in
      --task*         ) task="&task=${opt#*=}" ;;
      --num*          ) num="&num=${opt#*=}" ;;
      --concurrency*  ) con="&concurrency=${opt#*=}" ;;
      --retry*        ) retry="&retry=${opt#*=}" ;;
    esac
    shift
  done

  if [[ -z "${task}" ]]; then
    echo "Missing --task=TASK"
    exit 1
  fi

  echo curl -s "http://jobcontroller-default.kndev.us-south.containers.appdomain.cloud/create?job=$job${task}${num}${con}${retry}" > out
  curl -s "http://jobcontroller-default.kndev.us-south.containers.appdomain.cloud/create?job=$job${task}${num}${con}${retry}" > out
fi

if [[ "$1" == "wait" ]]; then
  shift
  job="$1"
  while true; do
    curl -s "http://jobcontroller-default.kndev.us-south.containers.appdomain.cloud/status?job=$job" > out
	if [[ "$(jq .NumJobs out)" == "$(jq .NumCompleted out)" ]]; then
      cat out
      break
    fi
    sleep 1
  done
fi

if [[ "$1" == "status" ]]; then
  shift
  job="$1"
  curl -s "http://jobcontroller-default.kndev.us-south.containers.appdomain.cloud/status?job=$job" > out
  if ( grep "$job" out > /dev/null ); then
    cat out
  else
    echo "Job '$job' not found"
  fi
fi
