apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: test
spec:
  template:
    metadata:
      labels:
        type: task
    spec:
      containers:
      - image: duglin/app
        imagePullPolicy: Always
